-- MySQL Script generated by MySQL Workbench
-- Sat Jun 10 21:00:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_final` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyecto_final` ;

-- -----------------------------------------------------
-- Table `proyecto_final`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final`.`Categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_final`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_final`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final`.`Proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuit` INT NOT NULL,
  `razon_social` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_final`.`Orden_de_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final`.`Orden_de_compra` (
  `nro_oc` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`nro_oc`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_proveedor` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `orden_de_compra_ibfk_2`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `proyecto_final`.`Clientes` (`id`),
  CONSTRAINT `orden_de_compra_ibfk_3`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `proyecto_final`.`Proveedores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_final`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `id_categoria` INT NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `precio_compra` FLOAT NOT NULL,
  `precio_venta` FLOAT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `proyecto_final`.`Categorias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_final`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final`.`Ventas` (
  `nro_fc` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `id_cliente` INT NOT NULL,
  `descuento` FLOAT NULL DEFAULT NULL,
  `total` FLOAT NULL DEFAULT NULL,
  `Orden_de_compra_nro_oc` INT NOT NULL,
  PRIMARY KEY (`nro_fc`, `Orden_de_compra_nro_oc`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_Ventas_Orden_de_compra1_idx` (`Orden_de_compra_nro_oc` ASC) VISIBLE,
  CONSTRAINT `ventas_ibfk_2`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `proyecto_final`.`Clientes` (`id`),
  CONSTRAINT `fk_Ventas_Orden_de_compra1`
    FOREIGN KEY (`Orden_de_compra_nro_oc`)
    REFERENCES `proyecto_final`.`Orden_de_compra` (`nro_oc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_final`.`Integra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final`.`Integra` (
  `Orden_de_compra_nro_oc` INT NOT NULL,
  `Productos_id` INT NOT NULL,
  PRIMARY KEY (`Orden_de_compra_nro_oc`, `Productos_id`),
  INDEX `fk_Orden_de_compra_has_Productos_Productos1_idx` (`Productos_id` ASC) VISIBLE,
  INDEX `fk_Orden_de_compra_has_Productos_Orden_de_compra1_idx` (`Orden_de_compra_nro_oc` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_de_compra_has_Productos_Orden_de_compra1`
    FOREIGN KEY (`Orden_de_compra_nro_oc`)
    REFERENCES `proyecto_final`.`Orden_de_compra` (`nro_oc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_de_compra_has_Productos_Productos1`
    FOREIGN KEY (`Productos_id`)
    REFERENCES `proyecto_final`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_final`.`Proveen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final`.`Proveen` (
  `Productos_id` INT NOT NULL,
  `Proveedores_id` INT NOT NULL,
  PRIMARY KEY (`Productos_id`, `Proveedores_id`),
  INDEX `fk_Productos_has_Proveedores_Proveedores1_idx` (`Proveedores_id` ASC) VISIBLE,
  INDEX `fk_Productos_has_Proveedores_Productos1_idx` (`Productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Proveedores_Productos1`
    FOREIGN KEY (`Productos_id`)
    REFERENCES `proyecto_final`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Proveedores_Proveedores1`
    FOREIGN KEY (`Proveedores_id`)
    REFERENCES `proyecto_final`.`Proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
